/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class StringOperationsTest {
    @Test void singlePangram() {
        StringOperations classUnderTest = new StringOperations();
        String testPalindrome= "The quick brown fox jumps over the lazy dog";

        assertTrue(classUnderTest.isPalindrome(testPalindrome));
    }

    @Test void singleNotPangram() {
        StringOperations classUnderTest = new StringOperations();
        String testPalindrome= "The quicsdsd over thsaddy dog";

        assertFalse(classUnderTest.isPalindrome(testPalindrome));
    }

    @Test void contact() {
        StringOperations classUnderTest = new StringOperations();

        assertEquals("testtest2", classUnderTest.concat("test", "test2"));
    }

    @Test void contactWhiteSpace() {
        StringOperations classUnderTest = new StringOperations();

        assertEquals("test  test2", classUnderTest.concat("test ", " test2"));
    }

    @Test void reverse() {
        StringOperations classUnderTest = new StringOperations();
        String testString= "abc";

        assertEquals("cba", classUnderTest.reverse(testString));
    }

    @Test void reverseSentence() {
        StringOperations classUnderTest = new StringOperations();
        String testString= "The quick brown fox jumps over the lazy dog";

        assertEquals("god yzal eht revo spmuj xof nworb kciuq ehT", classUnderTest.reverse(testString));
    }
}
